url: "https://ecorpus.eu"
baseurl: ""
title: "eCorpus"

toc: true

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "fr"
    values:
      lang: "fr"
  - scope:
      path: "en"
    values:
      lang: "en"

  - scope:
      path: "*/doc"
    values:
      layout: "doc"
      type: doc
  